'use server'
import { supabaseAdmin } from "@/lib/supabase";
import { CaptureResult } from "@/types/type";
import { v4 as uuidv4 } from 'uuid';
import type { UserResponse } from '@supabase/supabase-js';

export async function uploadImageToStorage(
    captureResult: CaptureResult,
    user: UserResponse['data']['user']
): Promise<{ success: boolean; message: string }> {

    if (!user || !user.id) {
        return { success: false, message: "User not authenticated" };
    }
    if (!captureResult.url) {
        return { success: false, message: "No image URL provided in captureResult" };
    }

    if (!captureResult.metadata) {
        return { success: false, message: "No metadata provided in captureResult" };
    }

    const base64String = captureResult.url.split(',')[1];
    if (!base64String) {
        return { success: false, message: "Invalid base64 URL format" };
    }

    const buffer = Buffer.from(base64String, 'base64');
    const contentType = captureResult.metadata.mimeType || captureResult.url.split(';')[0].split(':')[1] || 'image/jpeg';
    const timestamp = captureResult.metadata.capturedAt.replace(/[:.]/g, '-');
    const uniqueId = uuidv4().split('-')[0];
    const fileExtension = 'jpg';
    const path = `${timestamp}_${uniqueId}.${fileExtension}`;

    const file = new File([buffer], path, { type: contentType });

    if (!supabaseAdmin) {
        return { success: false, message: "Supabase client not initialized" };
    }

    const { error } = await supabaseAdmin.storage
        .from('Screenshots')
        .upload(path, file, {
            cacheControl: '3600',
            upsert: false,
            contentType: contentType,
            metadata: captureResult.metadata
        });

    if (error) {
        return { success: false, message: error.message || "Upload failed" };
    }

    const newPhoto = {
        // id is auto-generated by the database
        created_at: captureResult.metadata.capturedAt,
        image: path, // or use the full storage URL if needed
        uid: user!.id, // assuming metadata contains the user id
    };

    console.log('newPhoto:', newPhoto);

    const { error: insertError } = await supabaseAdmin
        .from('Photos')
        .insert([newPhoto]);

    if (insertError) {
        return { success: false, message: insertError.message || "Failed to insert photo record" };
    }

    return { success: true, message: "Upload successful!" };
}


export async function getPhotosFromUser(userId: string) {
    if (!userId) {
        return { success: false, message: "User ID is required", photos: [] };
    }

    if (!supabaseAdmin) {
        return { success: false, message: "Supabase client not initialized", photos: [] };
    }

    const { data, error } = await supabaseAdmin
        .from('Photos')
        .select('*')
        .eq('uid', userId)
        .order('created_at', { ascending: false });

    if (error) {
        return { success: false, message: error.message || "Failed to fetch photos", photos: [] };
    }

    return { success: true, message: "Photos fetched successfully", photos: data || [] };
}